AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Exported by architect/package@8.4.0 on 2023-02-03T14:22:15.443Z
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: ArcGlobalPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Resource: arn:aws:logs:*:*:*
      - PolicyName: ArcStaticBucketPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:DeleteObject
            - s3:ListBucket
            Resource:
            - Fn::Sub:
              - arn:aws:s3:::${bukkit}
              - bukkit:
                  Ref: StaticBucket
            - Fn::Sub:
              - arn:aws:s3:::${bukkit}/*
              - bukkit:
                  Ref: StaticBucket
      - PolicyName: ArcDynamoPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: dynamodb:*
            Resource:
            - Fn::Sub:
              - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tablename}
              - tablename:
                  Ref: TestdataTable
            - Fn::Sub:
              - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tablename}/*
              - tablename:
                  Ref: TestdataTable
            - Fn::Sub:
              - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tablename}
              - tablename:
                  Ref: AppRouterTable
            - Fn::Sub:
              - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tablename}/*
              - tablename:
                  Ref: AppRouterTable
          - Effect: Deny
            Action: dynamodb:DeleteTable
            Resource:
              Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*
  TestdataParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Fn::Sub:
        - /${AWS::StackName}/tables/${tablename}
        - tablename: testdata
      Value:
        Ref: TestdataTable
  AppRouterParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Fn::Sub:
        - /${AWS::StackName}/tables/${tablename}
        - tablename: AppRouter
      Value:
        Ref: AppRouterTable
  StaticBucketParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Fn::Sub:
        - /${AWS::StackName}/static/${key}
        - key: bucket
      Value:
        Ref: StaticBucket
  StaticFingerprintParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Fn::Sub:
        - /${AWS::StackName}/static/${key}
        - key: fingerprint
      Value: 'false'
  ParameterStorePolicy:
    Type: AWS::IAM::Policy
    DependsOn: Role
    Properties:
      PolicyName: ArcParameterStorePolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - ssm:GetParametersByPath
          - ssm:GetParameter
          Resource:
            Fn::Sub:
            - arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}
            - {}
        - Effect: Allow
          Action:
          - ssm:GetParametersByPath
          - ssm:GetParameter
          Resource:
            Fn::Sub:
            - arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/*
            - {}
        - Effect: Allow
          Action:
          - ssm:GetParametersByPath
          - ssm:GetParameter
          Resource:
            Fn::Sub:
            - arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/*/*
            - {}
      Roles:
      - Ref: Role
  HTTP:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      DefinitionBody:
        openapi: 3.0.1
        info:
          title:
            Ref: AWS::StackName
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                payloadFormatVersion: '2.0'
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetIndexHTTPLambda.Arn}/invocations
                connectionType: INTERNET
          /AuthCenter:
            post:
              x-amazon-apigateway-integration:
                payloadFormatVersion: '2.0'
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostAuthCenterHTTPLambda.Arn}/invocations
                connectionType: INTERNET
          /_static/{proxy+}:
            get:
              x-amazon-apigateway-integration:
                payloadFormatVersion: '1.0'
                type: http_proxy
                httpMethod: GET
                uri:
                  Fn::Sub:
                  - https://${bukkit}.s3.${AWS::Region}.amazonaws.com/{proxy}
                  - bukkit:
                      Ref: StaticBucket
                connectionType: INTERNET
                timeoutInMillis: 30000
  GetIndexHTTPLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://agape-arc-cfn-deployments-7ec3c/8ca5a5647defd57c71eff2d96ef6823a
      Runtime: nodejs16.x
      Architectures:
      - arm64
      MemorySize: 1152
      EphemeralStorage:
        Size: 512
      Timeout: 5
      Environment:
        Variables:
          ARC_APP_NAME: agape-arc
          ARC_ENV: production
          ARC_ROLE:
            Ref: Role
          ARC_SESSION_TABLE_NAME: jwe
          ARC_STACK_NAME:
            Ref: AWS::StackName
          ARC_STATIC_BUCKET:
            Ref: StaticBucket
          ARC_STATIC_SPA: false
          ARC_APP_SECRET: eyJrdHkiOiJvY3QiLCJrIjoidm9NV2oxMVhfT0xUTy1SUXpUdkQ0REFUbmwwbmpCZ25zVHBiU28tOWMtZyJ9
          JWT_B64_PRIVATE: eyJrdHkiOiJFQyIsIngiOiJtUUJrUjB1S251WDctVnlWMERyWHF3RUtGRm9mWXhKRVRDRHp6Z1oxSlFZIiwieSI6InhaLTVmV09aSkVKM0czb1ZMZUJwSXVYdnRqVmtoVGxJNUpWZEhiaVFzS2ciLCJjcnYiOiJQLTI1NiIsImQiOiJmMFFBNUdOck5RcThfVXBvV01vUFNJQTV0WkFlMzNzSzY3ODhJUzl0ZEE0In0=
          JWT_B64_PUBLIC: eyJrdHkiOiJFQyIsIngiOiJtUUJrUjB1S251WDctVnlWMERyWHF3RUtGRm9mWXhKRVRDRHp6Z1oxSlFZIiwieSI6InhaLTVmV09aSkVKM0czb1ZMZUJwSXVYdnRqVmtoVGxJNUpWZEhiaVFzS2ciLCJjcnYiOiJQLTI1NiJ9
      Role:
        Fn::Sub:
        - arn:aws:iam::${AWS::AccountId}:role/${roleName}
        - roleName:
            Ref: Role
      Events:
        GetIndexHTTPEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId:
              Ref: HTTP
    ArcMetadata:
      pragma: http
      name: get /
      method: get
      path: /
  PostAuthCenterHTTPLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://agape-arc-cfn-deployments-7ec3c/c91e0a68b0a793a29c0a9e6c9e1d4388
      Runtime: nodejs16.x
      Architectures:
      - arm64
      MemorySize: 1152
      EphemeralStorage:
        Size: 512
      Timeout: 5
      Environment:
        Variables:
          ARC_APP_NAME: agape-arc
          ARC_ENV: production
          ARC_ROLE:
            Ref: Role
          ARC_SESSION_TABLE_NAME: jwe
          ARC_STACK_NAME:
            Ref: AWS::StackName
          ARC_STATIC_BUCKET:
            Ref: StaticBucket
          ARC_APP_SECRET: eyJrdHkiOiJvY3QiLCJrIjoidm9NV2oxMVhfT0xUTy1SUXpUdkQ0REFUbmwwbmpCZ25zVHBiU28tOWMtZyJ9
          JWT_B64_PRIVATE: eyJrdHkiOiJFQyIsIngiOiJtUUJrUjB1S251WDctVnlWMERyWHF3RUtGRm9mWXhKRVRDRHp6Z1oxSlFZIiwieSI6InhaLTVmV09aSkVKM0czb1ZMZUJwSXVYdnRqVmtoVGxJNUpWZEhiaVFzS2ciLCJjcnYiOiJQLTI1NiIsImQiOiJmMFFBNUdOck5RcThfVXBvV01vUFNJQTV0WkFlMzNzSzY3ODhJUzl0ZEE0In0=
          JWT_B64_PUBLIC: eyJrdHkiOiJFQyIsIngiOiJtUUJrUjB1S251WDctVnlWMERyWHF3RUtGRm9mWXhKRVRDRHp6Z1oxSlFZIiwieSI6InhaLTVmV09aSkVKM0czb1ZMZUJwSXVYdnRqVmtoVGxJNUpWZEhiaVFzS2ciLCJjcnYiOiJQLTI1NiJ9
      Role:
        Fn::Sub:
        - arn:aws:iam::${AWS::AccountId}:role/${roleName}
        - roleName:
            Ref: Role
      Events:
        PostAuthCenterHTTPEvent:
          Type: HttpApi
          Properties:
            Path: /AuthCenter
            Method: POST
            ApiId:
              Ref: HTTP
    ArcMetadata:
      pragma: http
      name: post /AuthCenter
      method: post
      path: /AuthCenter
  TestdataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
      - AttributeName: oid
        KeyType: HASH
      AttributeDefinitions:
      - AttributeName: oid
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
  AppRouterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
      - AttributeName: oid
        KeyType: HASH
      AttributeDefinitions:
      - AttributeName: oid
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
  StaticBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerEnforced
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  StaticBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: StaticBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
          - Fn::Sub:
            - arn:aws:s3:::${bukkit}/*
            - bukkit:
                Ref: StaticBucket
          Sid: PublicReadGetObject
Outputs:
  API:
    Description: API Gateway (HTTP)
    Value:
      Fn::Sub:
      - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com
      - ApiId:
          Ref: HTTP
  ApiId:
    Description: API ID (ApiId)
    Value:
      Ref: HTTP
  BucketURL:
    Description: Bucket URL
    Value:
      Fn::Sub:
      - http://${bukkit}.s3-website-${AWS::Region}.amazonaws.com
      - bukkit:
          Ref: StaticBucket
